# run: conda env create --file environment.yml
name: ttrecipes
dependencies:
- python>=3.3
- pip
- numpy
- scipy
- six
- cython
- matplotlib
## Optional gFortran install with conda since some versions of gFortran 5.0-8.0 had a bug
## preventing a successful ttpy compilation
#- gcc<5.0|>=9.0
#- pip:
#  - git+https://github.com/oseledets/ttpy#egg=ttpy
