# run: conda env create --file environment.yml
name: ttrecipes
dependencies:
- python>=3.3
- pip
- numpy
- scipy
- six
- cython
- matplotlib
- gcc<5.0  ## Optional
- pip:
  - git+https://github.com/oseledets/ttpy#egg=ttpy-HEAD

